name: Deploy Static HTML to AWS S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
          
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Deploy HTML files to S3
        run: |
          aws s3 sync ./path-to-your-html-files s3://your-bucket-name --delete
